

export const types= {

  //AUTH ACTIONS//
	LOGIN_START         : 'LOGIN_START',
	LOGIN_SUCCESS       : 'LOGIN_SUCCESS',
  LOGIN_FAIL          : 'LOGIN_FAIL',
  
	CREATE_USER_START   : 'CREATE_USER_START',
	CREATE_USER_SUCCESS : 'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL    : 'CREATE_USER_FAIL',
  
	LOGOUT_START        : 'LOGOUT_START',
	LOGOUT_SUCCESS      : 'LOGOUT_SUCCESS',
	LOGOUT_FAIL         : 'LOGOUT_FAIL',
	
	GET_USER_START        : 'GET_USER_START',
	GET_USER_SUCCESS      : 'GET_USER_SUCCESS',
	GET_USER_FAIL         : 'GET_USER_FAIL',


  WELCOME_BACK        : 'WELCOME_BACK',
  //AUTH ACTIONS//



  
  //CRUD ACTIONS//
	GET_EQUIP_LIST_START     : 'GET_EQUIP_LIST_START',
	GET_EQUIP_LIST_SUCCESS   : 'GET_EQUIP_LIST_SUCCESS',
  GET_EQUIP_LIST_FAIL      : 'GET_EQUIP_LIST_FAIL',

  GET_MY_EQUIP_ITEM_START      : 'GET_MY_EQUIP_ITEM_START',
	GET_MY_EQUIP_ITEM_SUCCESS    : 'GET_MY_EQUIP_ITEM_SUCCESS',
  GET_MY_EQUIP_ITEM_FAIL       : 'GET_MY_EQUIP_ITEM_FAIL',
  

	POST_EQUIP_LIST_START    : 'POST_EQUIP_LIST_START',
	POST_EQUIP_LIST_SUCCESS  : 'POST_EQUIP_LIST_SUCCESS',
  POST_EQUIP_LIST_FAIL     : 'POST_EQUIP_LIST_FAIL',
  
  
	PUT_EQUIP_ITEM_START      : 'PUT_EQUIP_ITEM_START',
	PUT_EQUIP_ITEM_SUCCESS    : 'PUT_EQUIP_ITEM_SUCCESS',
  PUT_EQUIP_ITEM_FAIL       : 'PUT_EQUIP_ITEM_FAIL',
  

	DELETE_EQUIP_START   : 'DELETE_EQUIP_START',
	DELETE_EQUIP_SUCCESS : 'DELETE_EQUIP_SUCCESS',
  DELETE_EQUIP_FAIL    : 'DELETE_EQUIP_FAIL',
  //CRUD ACTIONS//
};